# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170429_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Detail User Profile', 'verbose_name_plural': 'Users'},
        ),
    ]
