# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 14:13
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170429_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload your photo for Avatar', null=True, upload_to=accounts.models.image_upload_to),
        ),
    ]
