# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 14:41
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload Avatar', null=True, upload_to=accounts.models.image_upload_to),
        ),
    ]
