# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 15:52
from __future__ import unicode_literals

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170429_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_user',
            field=models.FileField(blank=True, help_text='Upload Your CV', null=True, upload_to=accounts.models.image_upload_to),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="\n            Phone number must be entered in the format: '+999999999'.             Up to 15 digits allowed.\n        ", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
