# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 16:17
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0003_auto_20170429_1413'),
        ('accounts', '0012_auto_20170429_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companys.CompanyProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload Your Avatar', null=True, upload_to=accounts.models.image_upload_to),
        ),
    ]
