# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 11:39
from __future__ import unicode_literals

import companys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True)),
                ('website', models.CharField(blank=True, max_length=250, null=True)),
                ('logo', models.ImageField(upload_to=companys.models.image_upload_to)),
                ('size', models.CharField(choices=[('< 10', '< 10'), ('10 - 25', '10 - 25'), ('25 - 99', '25 - 99'), ('100 - 499', '100 - 499'), ('500 - 999', '500 - 999'), ('> 1000', '> 1000')], max_length=120)),
                ('email_contact', models.EmailField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Companys',
                'verbose_name': 'Detail Company Info',
            },
        ),
    ]
