# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 14:13
from __future__ import unicode_literals

import companys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_auto_20170429_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload logo for Company', null=True, upload_to=companys.models.image_upload_to),
        ),
    ]
