# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_userprofile_company'),
        ('companys', '0003_auto_20170429_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companys.CompanyProfile')),
            ],
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='user',
            field=models.ManyToManyField(through='companys.Membership', to='accounts.UserProfile'),
        ),
    ]
