# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0004_auto_20170429_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='user',
            new_name='member',
        ),
    ]
