# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0005_auto_20170429_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
