# from .utils import list_province_data


SIZE_COMPANY = (
    ('< 10', '< 10'),
    ('10 - 25', '10 - 25'),
    ('25 - 99', '25 - 99'),
    ('100 - 499', '100 - 499'),
    ('500 - 999', '500 - 999'),
    ('> 1000', '> 1000'),
)

CITY = (
    ('ha noi', 'Ha Noi'),
    ('ha giang', 'Ha Giang'),
    ('cao bang', 'Cao Bang'),
    ('bac kan', 'Bac Kan'),
    ('tuyen quang', 'Tuyen Quang'),
    ('lao cai', 'Lao Cai'),
    ('dien bien', 'Dien Bien'),
    ('lai chau', 'Lai Chau'),
    ('son la', 'Son La'),
    ('yen bai', 'Yen Bai'),
    ('hoa binh', 'Hoa Binh'),
    ('thai nguyen', 'Thai Nguyen'),
    ('lang son', 'Lang Son'),
    ('quang ninh', 'Quang Ninh'),
    ('bac giang', 'Bac Giang'),
    ('phu tho', 'Phu Tho'),
    ('vinh phuc', 'Vinh Phuc'),
    ('bac ninh', 'Bac Ninh'),
    ('hai duong', 'Hai Duong'),
    ('hai phong', 'Hai Phong'),
    ('hung yen', 'Hung Yen'),
    ('thai binh', 'Thai Binh'),
    ('ha nam', 'Ha Nam'),
    ('nam dinh', 'Nam Dinh'),
    ('ninh binh', 'Ninh Binh'),
    ('thanh hoa', 'Thanh Hoa'),
    ('nghe an', 'Nghe An'),
    ('ha tinh', 'Ha Tinh'),
    ('quang binh', 'Quang Binh'),
    ('quang tri', 'Quang Tri'),
    ('thua thien-hue', 'Thua Thien-Hue'),
    ('da nang', 'Da Nang'),
    ('quang nam', 'Quang Nam'),
    ('quang ngai', 'Quang Ngai'),
    ('binh dinh', 'Binh Dinh'),
    ('phu yen', 'Phu Yen'),
    ('khanh hoa', 'Khanh Hoa'),
    ('ninh thuan', 'Ninh Thuan'),
    ('binh thuan', 'Binh Thuan'),
    ('kon tum', 'Kon Tum'),
    ('gia lai', 'Gia Lai'),
    ('dak lak', 'Dak Lak'),
    ('dak nong', 'Dak Nong'),
    ('lam dong', 'Lam Dong'),
    ('binh phuoc', 'Binh Phuoc'),
    ('tay ninh', 'Tay Ninh'),
    ('binh duong', 'Binh Duong'),
    ('dong nai', 'Dong Nai'),
    ('ba ria-vung tau', 'Ba Ria-Vung Tau'),
    ('thanh pho ho chi minh', 'Thanh pho Ho Chi Minh'),
    ('long an', 'Long An'),
    ('tien giang', 'Tien Giang'),
    ('ben tre', 'Ben Tre'),
    ('tra vinh', 'Tra Vinh'),
    ('vinh long', 'Vinh Long'),
    ('dong thap', 'Dong Thap'),
    ('an giang', 'An Giang'),
    ('kien giang', 'Kien Giang'),
    ('can tho', 'Can Tho'),
    ('hau giang', 'Hau Giang'),
    ('soc trang', 'Soc Trang'),
    ('bac lieu', 'Bac Lieu'),
    ('ca mau', 'Ca Mau'),
)
