SIZE_COMPANY = (
    ('<10', '< 10'),
    ('10-25', '10 - 25'),
    ('25-99', '25 - 99'),
    ('100-499', '100 - 499'),
    ('500-999', '500 - 999'),
    ('>1000', '> 1000'),
)

CITY = (
    ('hanoi', 'Ha Noi'),
    ('hagiang', 'Ha Giang'),
    ('caobang', 'Cao Bang'),
    ('backan', 'Bac Kan'),
    ('tuyenquang', 'Tuyen Quang'),
    ('laocai', 'Lao Cai'),
    ('dienbien', 'Dien Bien'),
    ('laichau', 'Lai Chau'),
    ('sonla', 'Son La'),
    ('yenbai', 'Yen Bai'),
    ('hoabinh', 'Hoa Binh'),
    ('thainguyen', 'Thai Nguyen'),
    ('langson', 'Lang Son'),
    ('quangninh', 'Quang Ninh'),
    ('bacgiang', 'Bac Giang'),
    ('phutho', 'Phu Tho'),
    ('vinhphuc', 'Vinh Phuc'),
    ('bacninh', 'Bac Ninh'),
    ('haiduong', 'Hai Duong'),
    ('haiphong', 'Hai Phong'),
    ('hungyen', 'Hung Yen'),
    ('thaibinh', 'Thai Binh'),
    ('hanam', 'Ha Nam'),
    ('namdinh', 'Nam Dinh'),
    ('ninhbinh', 'Ninh Binh'),
    ('thanhhoa', 'Thanh Hoa'),
    ('nghean', 'Nghe An'),
    ('hatinh', 'Ha Tinh'),
    ('quangbinh', 'Quang Binh'),
    ('quangtri', 'Quang Tri'),
    ('thuathien-hue', 'Thua Thien-Hue'),
    ('danang', 'Da Nang'),
    ('quangnam', 'Quang Nam'),
    ('quangngai', 'Quang Ngai'),
    ('binhdinh', 'Binh Dinh'),
    ('phuyen', 'Phu Yen'),
    ('khanhhoa', 'Khanh Hoa'),
    ('ninhthuan', 'Ninh Thuan'),
    ('binhthuan', 'Binh Thuan'),
    ('kontum', 'Kon Tum'),
    ('gialai', 'Gia Lai'),
    ('daklak', 'Dak Lak'),
    ('daknong', 'Dak Nong'),
    ('lamdong', 'Lam Dong'),
    ('binhphuoc', 'Binh Phuoc'),
    ('tayninh', 'Tay Ninh'),
    ('binhduong', 'Binh Duong'),
    ('dongnai', 'Dong Nai'),
    ('baria-vungtau', 'Ba Ria-Vung Tau'),
    ('thanhphohochiminh', 'Thanh pho Ho Chi Minh'),
    ('longan', 'Long An'),
    ('tiengiang', 'Tien Giang'),
    ('bentre', 'Ben Tre'),
    ('travinh', 'Tra Vinh'),
    ('vinhlong', 'Vinh Long'),
    ('dongthap', 'Dong Thap'),
    ('angiang', 'An Giang'),
    ('kiengiang', 'Kien Giang'),
    ('cantho', 'Can Tho'),
    ('haugiang', 'Hau Giang'),
    ('soctrang', 'Soc Trang'),
    ('baclieu', 'Bac Lieu'),
    ('camau', 'Ca Mau'),
)
