# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'Detail Sign Up', 'verbose_name_plural': 'Signup'},
        ),
    ]
