# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newletters', '0002_auto_20170429_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='timestamp',
            new_name='created',
        ),
    ]
