# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newletters', '0003_auto_20170429_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'Detail Sign Up', 'verbose_name_plural': 'SignUps'},
        ),
    ]
