# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companys', '0003_auto_20170429_1413'),
        ('accounts', '0014_remove_userprofile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exriry_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('wage', models.CharField(blank=True, choices=[('< 5.000.000', '< 5.000.000'), ('5.000.000 -> 10.000.000', '5.000.000 -> 10.000.000'), ('10.000.000 -> 15.000.000', '10.000.000 -> 15.000.000'), ('15.000.000 -> 20.000.000', '15.000.000 -> 20.000.000'), ('20.000.000 -> 25.000.000', '20.000.000 -> 25.000.000'), ('25.000.000 -> 30.000.000', '25.000.000 -> 30.000.000'), ('> 30.000.000', '> 30.000.000')], max_length=100, null=True)),
                ('welfare', models.TextField(blank=True, max_length=250, null=True)),
                ('skill', models.TextField(blank=True, max_length=250, null=True)),
                ('work', models.TextField(blank=True, max_length=250, null=True)),
                ('url', models.URLField(blank=True, max_length=250, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companys.CompanyProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
            options={
                'verbose_name': 'Detail Jobs Info',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
