# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsinfo',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='job_type',
            field=models.CharField(blank=True, choices=[('fulltime', 'FULLTIME'), ('parttime', 'PARTTIME'), ('remote', 'REMOTE'), ('internship', 'INTERNSHIP')], default='FULL TIME', max_length=100, null=True),
        ),
    ]
