# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20170429_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsinfo',
            name='company',
        ),
    ]
