# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobsinfo_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
