# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20170429_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsinfo',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
