# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20170429_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsDetailRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='jobsinfo',
            name='experience',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
