# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20170429_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsinfo',
            name='work',
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='experience',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
